#!/usr/bin/env sh
set -e

cd $DROPFILE_HOME

JAVA_PATH="$DROPFILE_HOME/runtime/bin/java"
JAR_PATH="$DROPFILE_HOME/dropfile-daemon/dropfile-daemon.jar"
LOG_PATH=$DROPFILE_HOME/logs
SPRING_APPLICATION_PROPERTIES_PATH="$DROPFILE_HOME/conf/dropfile-daemon.application.properties"

$JAVA_PATH "-Dlogging.path=$LOG_PATH" -XX:ActiveProcessorCount=1 -Xmx256m -Xms256m -jar $JAR_PATH "--spring.config.location=file:$SPRING_APPLICATION_PROPERTIES_PATH" $*
