#!/usr/bin/env sh
set -e

REAL_SCRIPT_PATH=$(realpath "$0" 2>/dev/null || readlink -f "$0")
SCRIPT_DIR=$(dirname -- "$REAL_SCRIPT_PATH")
APPLICATION_HOME=$(dirname -- "$SCRIPT_DIR")

CLI_DIR="$APPLICATION_HOME/jars/cli"
ORIGINAL_JAR="$CLI_DIR/dropfile-cli.jar"
CDS_DIR="$CLI_DIR/cds"
CDS_JAR="$CDS_DIR/dropfile-cli.jar"
JSA_PATH="$CDS_DIR/dropfile-cli.jsa"

JAVA_PATH="$APPLICATION_HOME/runtime/bin/java"
SPRING_APPLICATION_PROPERTIES_PATH="$APPLICATION_HOME/conf/dropfile-cli.application.properties"

DROPFILE_DAEMON_DAEMON_SECRETS_DIRECTORY="${DROPFILE_DAEMON_DAEMON_SECRETS_DIRECTORY:-$APPLICATION_HOME/conf}"
DROPFILE_DAEMON_INSTALLATION_SEED_DIRECTORY="${DROPFILE_DAEMON_INSTALLATION_SEED_DIRECTORY:-$APPLICATION_HOME/conf}"

DROPFILE_CLI_CPU_COUNT="${DROPFILE_CLI_CPU_COUNT:-1}"
DROPFILE_CLI_RAM_MB_XMX="${DROPFILE_CLI_RAM_MB_XMX:-128}"
DROPFILE_CLI_RAM_MB_XMS="${DROPFILE_CLI_RAM_MB_XMS:-64}"

if [ ! -f "$JSA_PATH" ]; then
    echo "[dropfile] First run detected. Optimizing application startup time..."

    rm -rf "$CDS_DIR"

    "$JAVA_PATH" -Djarmode=tools -jar "$ORIGINAL_JAR" extract --destination "$CDS_DIR" >/dev/null 2>&1

    "$JAVA_PATH" \
        "-XX:ActiveProcessorCount=$DROPFILE_CLI_CPU_COUNT" \
        "-Xmx${DROPFILE_CLI_RAM_MB_XMX}m" \
        "-Xms${DROPFILE_CLI_RAM_MB_XMS}m" \
        "-XX:ArchiveClassesAtExit=$JSA_PATH" \
        "-Dspring.context.exit=on" \
        "-Ddropfile.home=$APPLICATION_HOME" \
        "-Dspring.config.location=file:$SPRING_APPLICATION_PROPERTIES_PATH" \
        "-Ddropfile.daemon.daemon-secrets.directory=$DROPFILE_DAEMON_DAEMON_SECRETS_DIRECTORY" \
        "-Ddropfile.daemon.installation-seed.directory=$DROPFILE_DAEMON_INSTALLATION_SEED_DIRECTORY" \
        -jar "$CDS_JAR" >/dev/null 2>&1

    echo "[dropfile] Optimization completed successfully!"
fi

exec "$JAVA_PATH" \
    "-XX:ActiveProcessorCount=$DROPFILE_CLI_CPU_COUNT" \
    "-Xmx${DROPFILE_CLI_RAM_MB_XMX}m" \
    "-Xms${DROPFILE_CLI_RAM_MB_XMS}m" \
    "-XX:SharedArchiveFile=$JSA_PATH" \
    "-Ddropfile.home=$APPLICATION_HOME" \
    "-Dspring.config.location=file:$SPRING_APPLICATION_PROPERTIES_PATH" \
    "-Ddropfile.daemon.daemon-secrets.directory=$DROPFILE_DAEMON_DAEMON_SECRETS_DIRECTORY" \
    "-Ddropfile.daemon.installation-seed.directory=$DROPFILE_DAEMON_INSTALLATION_SEED_DIRECTORY" \
    -jar "$CDS_JAR" \
    "$@"