#!/usr/bin/env sh
set -e

cd $DROPFILE_HOME

JAVA_PATH="$DROPFILE_HOME/runtime/bin/java"
JAR_PATH="$DROPFILE_HOME/dropfile-cli/dropfile-cli.jar"
SPRING_APPLICATION_PROPERTIES_PATH="$DROPFILE_HOME/conf/dropfile-cli.application.properties"

$JAVA_PATH -XX:ActiveProcessorCount=1 -Xmx128m -Xms128m -jar $JAR_PATH "--spring.config.location=file:$SPRING_APPLICATION_PROPERTIES_PATH" $*
