#!/usr/bin/env sh
set -e

JAVA_PATH="$DROPFILE_HOME/runtime/bin/java"
JAR_PATH="$DROPFILE_HOME/dropfile-cli/dropfile-cli.jar"

$JAVA_PATH -XX:ActiveProcessorCount=1 -Xmx128m -Xms128m -jar $JAR_PATH $*