spring.application.name=dropfile-daemon
spring.profiles.active=prod
spring.mvc.async.request-timeout=360000

dropfile.daemon.application-home.directory=${user.dir}
dropfile.daemon.daemon-secrets.directory=${dropfile.daemon.application-home.directory}/conf
dropfile.daemon.installation-seed.directory=${dropfile.daemon.application-home.directory}/conf
dropfile.daemon.downloads.directory=${dropfile.daemon.application-home.directory}/downloads

dropfile.daemon.download.orchestrator.max-queue-size=1000
dropfile.daemon.download.orchestrator.active-queue-size=10
dropfile.daemon.download.procedure.thread-size=2
dropfile.daemon.handshake.client.http.request-timeout-millis=60000
dropfile.daemon.handshake.server.payload.life-time=30000
dropfile.daemon.tunnel.client.compress.enabled=true
dropfile.daemon.tunnel.client.stream.max-size=10485760
dropfile.daemon.tunnel.client.stream.deadline-timeout-millis=360000
dropfile.daemon.tunnel.client.http.request-timeout-millis=60000
dropfile.daemon.tunnel.server.compress.level=3
dropfile.daemon.tunnel.server.payload.life-time=30000
dropfile.daemon.quick-share.secure.compress.level=3
dropfile.daemon.quick-share.async.request-timeout=86400000
dropfile.daemon.quick-share.insecure.compress.enabled=true
dropfile.daemon.quick-share.insecure.compress.level=3
dropfile.daemon.gc.rate-millis=60000

dropfile.daemon.manifest.chunk-max-size=4194304

server.port=18181