spring.application.name=dropfile-daemon
spring.profiles.active=prod

dropfile.download.directory=${user.dir}/downloads
dropfile.daemon.port=18181
dropfile.file.operations.buffer-size=1048576
dropfile.download.orchestrator.max-queue-size=1000
dropfile.download.orchestrator.active-queue-size=10
dropfile.download.procedure.thread-size=2
dropfile.handshake.client.http.request-timeout-millis=60000
dropfile.handshake.server.payload.life-time=30000
dropfile.tunnel.client.compress.enabled=true
dropfile.tunnel.client.stream.max-size=10485760
dropfile.tunnel.client.stream.deadline-timeout-millis=360000
dropfile.tunnel.client.http.request-timeout-millis=60000
dropfile.tunnel.server.compress.level=3
dropfile.tunnel.server.payload.life-time=30000

dropfile.manifest.chunk-max-size=4194304
dropfile.manifest.builder.buffer-size=65536

server.port=${dropfile.daemon.port}

spring.mvc.async.request-timeout=360000