spring.application.name=dropfile-daemon

dropfile.download.directory=${user.dir}/downloads
dropfile.daemon.port=28282
dropfile.file.operations.buffer-size=1048576
dropfile.daemon.token=daemon-token-dev
dropfile.download.procedure.thread-size=2
dropfile.download.procedure.manifest.call.timeout-millis=120000
dropfile.download.procedure.chunk.call.timeout-millis=60000
dropfile.tunnel.compress.enabled=true
dropfile.tunnel.compress.level=3

dropfile.manifest-builder.chunk-size=4194304
dropfile.manifest-builder.buffer-size=65536

server.port=${dropfile.daemon.port}

spring.mvc.async.request-timeout=300000