spring.application.name=dropfile-daemon

dropfile.application.directory=${user.dir}
dropfile.download.directory=${dropfile.application.directory}/downloads
dropfile.daemon.port=28282
dropfile.daemon.token=daemon-token-dev
dropfile.download.procedure.thread-size=2
dropfile.download.procedure.manifest.call.timeout-millis=120000
dropfile.download.procedure.chunk.call.timeout-millis=60000
dropfile.tunnel.compress.enabled=true
dropfile.tunnel.compress.level=3

file.manifest.builder.chunk.size=4194304
file.manifest.builder.buffer.size=65536

server.port=${dropfile.daemon.port}

spring.mvc.async.request-timeout=300000