spring.application.name=dropfile-cli
spring.main.banner-mode=off
logging.level.root=WARN
spring.profiles.active=prod

dropfile.application.directory=${user.dir}
dropfile.daemon.host=127.0.0.1
dropfile.daemon.port=18181

#logging.level.com.evolution.dropfilecli.command=DEBUG