spring.application.name=dropfile-cli
spring.main.banner-mode=off
logging.level.root=WARN
spring.profiles.active=prod

dropfile.daemon.secrets.dir=${user.dir}/conf
dropfile.daemon.installation.seed.dir=${user.dir}/conf
dropfile.daemon.host=127.0.0.1
dropfile.daemon.port=18181

#logging.level.com.evolution.dropfilecli.command=DEBUG